version: "3.8"
services:
  app:
    stdin_open: true
    container_name: nktc-stu-app
    image: nktc-stu-app
    build:
      context: .
      # for deployment on production, use the following:
      dockerfile: dockerfile.prod
    restart: always
    ports:
      - 3000:3000
networks:
  default:
    name: nktc_stu
    external: true
