version: "3.8"
services:
  app:
    stdin_open: true
    container_name: nktc-stu-app
    image: nktc-stu-app
    build:
      context: .
      # for deployment on production, use the following:
      dockerfile: dockerfile.prod
      # for deployment on local, use the following:
      # dockerfile: dockerfile.dev
      # volumes:
      #   - .:/app
      #   - /app/node_modules
      #   - /app/.next
    networks:
      default:
      nktc_stu:
        ipv4_address: 172.19.0.20
    ports:
      - 3000:3000
networks:
  nktc_stu:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
volumes:
  dependencies:
    driver: local
