version: "3.8"

services:
  api:
    stdin_open: true
    container_name: nktc-stu-backend
    image: nktc-stu-backend
    build:
      context: .
      # for deployment on production, use the following:
      dockerfile: dockerfile.prod
    # restart: always
    env_file:
      - .env
    ports:
      - 3001:3001

networks:
  default:
    name: nktc_stu
    external: true
