version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Bangkok
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${POSTGRES_USER}',
          '-d',
          '${POSTGRES_DB}'
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
