version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - npm_nktc_stu
  api:
    stdin_open: true
    container_name: nktc-stu-backend
    image: nktc-stu-backend
    build:
      context: .
      # for deployment on production, use the following:
      dockerfile: dockerfile.prod
    # restart: always
    env_file:
      - .env
    ports:
      - 3001:3001

networks:
  default:
    name: npm_nktc_stu
    external: true
