import * as yup from 'yup';
export interface Survey {
  type: string;
  name: string;
  title: string;
  description?: string;
  required: boolean;
  choices?: string[];
  showOtherItem?: boolean;
  otherPlaceholder?: string;
  otherText?: string;
  otherOptions?: string[];
}

export const surveyList: Survey[] = [
  {
    type: 'radiogroup',
    name: 'address',
    title: '1.บ้านที่อาศัย',
    required: true,
    choices: ['บ้านตัวเอง', 'อาศัยอยู่กับผู้อื่น(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'อาศัยอยู่กับผู้อื่น(ระบุ)',
    otherText: 'อาศัยอยู่กับผู้อื่น(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'address-type',
    title: '2.ลักษณะบ้าน',
    required: true,
    choices: ['บ้านชั้นเดียว', 'บ้านสองชั้น', 'ลักษณะแบบอื่น ๆ (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'ลักษณะแบบอื่น ๆ (ระบุ)',
    otherText: 'ลักษณะแบบอื่น ๆ (ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'environment',
    title: '3.สภาพแวดล้อม',
    required: true,
    choices: ['ดี', 'พอใช้', 'ไม่ดี', 'ควรปรับปรุง (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'ควรปรับปรุง (ระบุ)',
    otherText: 'ควรปรับปรุง (ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'parents-status',
    title: '4.สถานภาพบิดา มารดา',
    required: true,
    choices: [
      'บิดามารดาอยู่ด้วยกัน',
      'บิดามารดาหย่าร้างกัน',
      'บิดาถึงแก่กรรม',
      'มารดาถึงแก่กรรม',
      'บิดาและมารดาถึงแก่กรรม',
    ],
    showOtherItem: false,
    otherPlaceholder: '',
    otherText: '',
  },
  {
    type: 'radiogroup',
    name: 'parents-living-condition',
    title: '5.อาชีพบิดา มารดา',
    required: true,
    choices: ['อยู่ร่วมกับบิดามารดา', 'อยู่กับบิดา', 'อยู่กับมารดา', 'อยู่ตามลำพัง', 'อยู่กับผู้อื่น (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'อยู่กับผู้อื่น (ระบุ)',
    otherText: 'อยู่กับผู้อื่น (ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'parents-workplace',
    title: '6.สถานที่ทำงานของบิดามารดา',
    required: true,
    choices: ['ในอำเภอเดียวกัน', 'ในจังหวัดเดียวกัน', 'ต่างจังหวัด(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'ต่างจังหวัด(ระบุ)',
    otherText: 'ต่างจังหวัด(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'parents',
    title: '7.ผู้ปกครอง',
    required: true,
    choices: ['บิดา', 'มารดา', 'บุคคลอื่น(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'บุคคลอื่น(ระบุ)',
    otherText: 'บุคคลอื่น(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'parents-occupation',
    title: '8.อาชีพของผู้ปกครอง',
    required: true,
    choices: ['เกษตรกร', 'ค้าขาย', 'รับราชการ', 'รับจ้าง', 'อื่น ๆ (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ (ระบุ)',
    otherText: 'อื่น ๆ (ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'family-income',
    title: '9.รายได้ของครอบครัวต่อปี',
    required: true,
    choices: [
      'น้อยกว่า 40,000 บาท',
      '40,001-100,000 บาท',
      '100,001 - 200,000 บาท',
      '200,001 - 360,000 บาท',
      '360,001-500,000 บาท',
      '500,000 ขึ้นไป',
    ],
    showOtherItem: false,
    otherPlaceholder: '',
    otherText: '',
  },
  {
    type: 'radiogroup',
    name: 'family-income-and-expenses',
    title: '10.รายได้กับการใช้จ่ายในครอบครัว',
    required: true,
    choices: ['เพียงพอ', 'ไม่เพียงพอในบางครั้ง', 'ขัดสน'],
    showOtherItem: false,
    otherPlaceholder: '',
    otherText: '',
  },
  {
    type: 'radiogroup',
    name: 'extra-income',
    title: '11.การหารายได้พิเศษของนักเรียน',
    required: true,
    choices: ['ไม่มีรายได้พิเศษ', 'มีรายได้พิเศษ(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'มีรายได้พิเศษ(ระบุ)',
    otherText: 'มีรายได้พิเศษ(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'family-relationship',
    title: '12.ความสัมพันธ์ของสมาชิกในครอบครัว',
    required: true,
    choices: ['อบอุ่น', 'เฉย ๆ', 'ห่างเหิน', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'radiogroup',
    name: 'parents-feeling',
    title: '13.ความรู้สึกของผู้ปกครองที่มีต่อนักเรียน',
    required: true,
    choices: ['พอใจ', 'เฉย ๆ', 'ไม่พอใจ', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'radiogroup',
    name: 'parents-raising',
    title: '14.วิธีการที่ผู้ปกครองอบรมเลี้ยงดูนักเรียน',
    required: true,
    choices: ['เข้มงวดกวดขัน', 'ตามใจ', 'ใช้เหตุผล', 'ปล่อยปละละเลย', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'checkbox',
    name: 'student-behavior',
    title: '15.การปฏิบัติตนของนักเรียนขณะอยู่ที่บ้าน',
    description: 'เลือกได้มากกว่า 1 รายการ',
    required: true,
    choices: ['อ่านหนังสือทำการบ้าน', 'ช่วยงานผู้ปกครอง', 'ทำงานบ้าน', 'ไม่ช่วยงานเลย', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'radiogroup',
    name: 'student-responsibility',
    title: '16.หน้าที่รับผิดชอบของนักเรียนภายในบ้าน',
    required: true,
    choices: ['ไม่มี', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'radiogroup',
    name: 'friend-type',
    title: '17.ลักษณะเพื่อนเล่นที่บ้านของนักเรียน',
    required: true,
    choices: ['เพื่อนรุ่นเดียวกัน', 'เพื่อนรุ่นน้อง', 'เพื่อนรุ่นพี่', 'เพื่อนทุกรุ่น'],
    showOtherItem: false,
    otherPlaceholder: '',
    otherText: '',
  },
  {
    type: 'radiogroup',
    name: 'friend-close',
    title: '18.เพื่อนสนิทของนักเรียน',
    required: true,
    choices: ['ไม่มี', 'มีเพื่อนสนิท(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'มีเพื่อนสนิท(ระบุ)',
    otherText: 'มีเพื่อนสนิท(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'travel-to-school',
    title: '19.การเดินทางมาโรงเรียนของนักเรียน',
    required: true,
    choices: ['เดิน', 'รถจักรยาน', 'รถจักยานยนต์', 'รถรับส่ง/รถโดยสาร', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  // {
  //   type: 'text',
  //   name: 'travel-to-school-money',
  //   title: '20.นักเรียนได้เงินมาโรงเรียนวันละ',
  //   required: true,
  // },
  {
    type: 'radiogroup',
    name: 'parents-need-when-student-graduate',
    title: '21.ความต้องการของผู้ปกครอง เมื่อนักเรียนเรียนจบชั้นสูงสุดของโรงเรียน',
    required: true,
    choices: ['ศึกษาต่อ', 'ประกอบอาชีพ', 'อื่น ๆ'],
    showOtherItem: true,
    otherPlaceholder: 'อื่น ๆ',
    otherText: 'อื่น ๆ',
  },
  {
    type: 'radiogroup',
    name: 'parents-opinion-next-year',
    title: '22.ปีการศึกษาถัดไป ผู้ปกครองมีความประสงค์ให้นักเรียน',
    required: true,
    choices: ['ศึกษาต่อสถานศึกษาเดิม', 'ศึกษาต่อสถานศึกษาแห่งใหม่', 'ไม่ศึกษาต่อ', 'จบการศึกษาชั้นสูงสุดแล้ว'],
    showOtherItem: false,
    otherPlaceholder: '',
    otherText: '',
  },
  {
    type: 'radiogroup',
    name: 'parents-satisfaction',
    title: '23.ความพึงพอใจของผู้ปกครองต่อโรงเรียน',
    required: true,
    choices: ['พอใจ', 'เฉย ๆ', 'ไม่พอใจ(ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'ไม่พอใจ(ระบุ)',
    otherText: 'ไม่พอใจ(ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'family-close',
    title: '24.ในครอบครัวนักเรียนสนิทสนมใครมากที่สุด',
    required: true,
    choices: ['พ่อ', 'แม่', 'พี่', 'น้อง', 'บุคคลอื่น (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'บุคคลอื่น (ระบุ)',
    otherText: 'บุคคลอื่น (ระบุ)',
  },
  {
    type: 'radiogroup',
    name: 'problem-who',
    title: '25.เมื่อมีปัญหา นักเรียนจะปรึกษาใคร',
    required: true,
    choices: ['พ่อ', 'แม่', 'พี่', 'น้อง', 'บุคคลอื่น (ระบุ)'],
    showOtherItem: true,
    otherPlaceholder: 'บุคคลอื่น (ระบุ)',
    otherText: 'บุคคลอื่น (ระบุ)',
  },
  {
    type: 'radiogroup-allow-other',
    name: 'behavior-drug',
    title: '26.พฤติกรรมใช้สารเสพติด',
    required: true,
    choices: ['ไม่มี', 'มีพฤติกรรมเสี่ยง(ระบุ)'],
    showOtherItem: true,
    otherText: 'มีพฤติกรรมเสี่ยง(ระบุ)',
    otherOptions: [
      'คบเพื่อนในกลุ่มที่ใช้สารเสพติด',
      'สมาชิกในครอบครัวข้องเกี่ยวกับยาเสพติด',
      'อยู่ในสภาพแวดดล้อมที่ใช้สารเสพติด',
      'ปัจจุบันเกี่ยวข้องกับสารเสพติด',
      'เป็นผู้ติดบุหรี่สุรา หรือการใช้สารเสพติดอื่นๆ',
    ]
  },
  {
    type: 'radiogroup-allow-other',
    name: 'behavior-violence',
    title: '27.พฤติกรรมใช้ความรุนแรง',
    required: true,
    choices: ['ไม่มี', 'มีพฤติกรรมใช้ความรุนแรง(ระบุ)'],
    showOtherItem: true,
    otherText: 'มีพฤติกรรมใช้ความรุนแรง(ระบุ)',
    otherOptions: [
      'มีการทะเลาะวิวาท',
      'ก้าวร้าว เกเร',
      'ทะเลาะวิวาทเป็นประจำ',
      'ทำร้ายร่างกายผู้อื่น',
      'ทำร้ายร่างกายตนเอง',
    ]
  },
  {
    type: 'radiogroup-allow-other',
    name: 'sexual-behavior',
    title: '28.พฤติกรรมทางเพศ',
    required: true,
    choices: ['ไม่มี', 'มีพฤติกรรมทางเพศ(ระบุ)'],
    showOtherItem: true,
    otherText: 'มีพฤติกรรมทางเพศ(ระบุ)',
    otherOptions: [
      'อยู่ในกลุ่มขายบริการ',
      'ขายบริการทางเพศ',
      'มีการมั่วสุมทางเพศ',
      'ตั้งครรภ์',
      'หมกมุ่นในการใช้เครื่องมือสื่อสารที่เกี่ยวข้องทางเพศ',
    ]
  },
  {
    type: 'radiogroup-allow-other',
    name: 'addict-game',
    title: '29.พฤติกรรมติดเกมส์',
    required: true,
    choices: ['ไม่มี', 'มีพฤติกรรมติดเกมส์(ระบุ)'],
    showOtherItem: true,
    otherText: 'มีพฤติกรรมติดเกมส์(ระบุ)',
    otherOptions: [
      'เล่นเกมเกินวันละ 3 ชั่วโมง',
      'อยู่ในกลุ่มเพื่อนเล่นเกม',
      'ร้านเกมส์อยู่ใกล้บ้าน',
      'ใช้จ่ายเงินผิดปกติ',
      'หมกมุ่น จริงจังในการเล่นเกมส์',
    ]
  },
  {
    type: 'radiogroup',
    name: 'internet-access',
    title: '30.การเข้าถึงสื่อคอมพิวเตอร์และอินเตอร์เน็ตที่บ้าน',
    required: true,
    choices: ['ไม่มีอินเตอร์เน็ต', 'เข้าถึงอินเตอร์เน็ตได้จาก(ระบุ)'],
    showOtherItem: true,
    otherText: 'เข้าถึงอินเตอร์เน็ตได้จาก(ระบุ)',
    otherPlaceholder: 'เข้าถึงอินเตอร์เน็ตได้จาก',
  },
  {
    type: 'radiogroup',
    name: 'mobile-phone',
    title: '31.การใช้โทรศัพท์มือถือ',
    required: true,
    choices: ['ไม่มีโทรศัพท์มือถือ', 'มีโทรศัพท์มือถือ เบอร์โทร'],
    showOtherItem: true,
    otherText: 'มีโทรศัพท์มือถือ เบอร์โทร',
    otherPlaceholder: 'มีโทรศัพท์มือถือ เบอร์โทร',
  },
];

export const defaultValues = {
  'address': '',
  'address-type': '',
  'environment': '',
  'parents-status': '',
  'parents-living-condition': '',
  'parents-workplace': '',
  'parents': '',
  'parents-occupation': '',
  'family-income': '',
  'family-income-and-expenses': '',
  'extra-income': '',
  'family-relationship': '',
  'parents-feeling': '',
  'parents-raising': '',
  'student-behavior': ['อื่น ๆ','ddd'],
  'student-responsibility': '',
  'friend-type': '',
  'friend-close': '',
  'travel-to-school': '',
  'travel-to-school-money': '',
  'parents-need-when-student-graduate': '',
  'parents-opinion-next-year': '',
  'parents-satisfaction': '',
  'family-close': '',
  'problem-who': '',
  'behavior-drug': '',
  'behavior-violence': '',
  'sexual-behavior': '',
  'addict-game': '',
  'internet-access': '',
  'mobile-phone': ''
};

export const schema = yup.object().shape({
  address: yup.string().required('กรุณาเลือกบ้านที่อาศัย'),
  'address-type': yup.string().required('กรุณาเลือกลักษณะบ้าน'),
  environment: yup.string().required('กรุณาเลือกสภาพแวดล้อม'),
  'parents-status': yup.string().required('กรุณาเลือกสถานภาพบิดา มารดา'),
  'parents-living-condition': yup.string().required('กรุณาเลือกอาชีพบิดา มารดา'),
  'parents-workplace': yup.string().required('กรุณาเลือกสถานที่ทำงานของบิดามารดา'),
  parents: yup.string().required('กรุณาเลือกผู้ปกครอง'),
  'parents-occupation': yup.string().required('กรุณาเลือกอาชีพของผู้ปกครอง'),
  'family-income': yup.string().required('กรุณาเลือกรายได้ของครอบครัวต่อปี'),
  'family-income-and-expenses': yup.string().required('กรุณาเลือกรายได้กับการใช้จ่ายในครอบครัว'),
  'extra-income': yup.string().required('กรุณาเลือกการหารายได้พิเศษของนักเรียน'),
  'family-relationship': yup.string().required('กรุณาเลือกความสัมพันธ์ของสมาชิกในครอบครัว'),
  'parents-feeling': yup.string().required('กรุณาเลือกความรู้สึกของผู้ปกครองที่มีต่อนักเรียน'),
  'parents-raising': yup.string().required('กรุณาเลือกวิธีการที่ผู้ปกครองอบรมเลี้ยงดูนักเรียน'),
  // 'student-behavior': yup.lazy(value =>
  //   Array.isArray(value)
  //     ? yup.array().of(yup.string()).required('กรุณาเลือกการปฏิบัติตนของนักเรียนขณะอยู่ที่บ้าน').nullable()
  //     : yup.string().required('กรุณาเลือกการปฏิบัติตนของนักเรียนขณะอยู่ที่บ้าน').nullable()
  // ),

  'student-behavior': yup.array().min(1, 'กรุณาเลือกการปฏิบัติตนของนักเรียนขณะอยู่ที่บ้าน').required('กรุณาเลือกการปฏิบัติตนของนักเรียนขณะอยู่ที่บ้าน')
    .nullable(),
  'student-responsibility': yup.string().required('กรุณาเลือกหน้าที่รับผิดชอบของนักเรียนภายในบ้าน'),
  'friend-type': yup.string().required('กรุณาเลือกลักษณะเพื่อนเล่นที่บ้านของนักเรียน'),
  'friend-close': yup.string().required('กรุณาเลือกเพื่อนสนิทของนักเรียน'),
  'travel-to-school': yup.string().required('กรุณาเลือกการเดินทางมาโรงเรียนของนักเรียน'),
  // 'travel-to-school-money': yup.string().required('กรุณากรอกนักเรียนได้เงินมาโรงเรียนวันละ'),
  'parents-need-when-student-graduate': yup.string().required('กรุณาเลือกความต้องการของผู้ปกครอง เมื่อนักเรียนเรียนจบชั้นสูงสุดของโรงเรียน'),
  'parents-opinion-next-year': yup.string().required('กรุณาเลือกปีการศึกษาถัดไป ผู้ปกครองมีความประสงค์ให้นักเรียน'),
  'parents-satisfaction': yup.string().required('กรุณาเลือกความพึงพอใจของผู้ปกครองต่อโรงเรียน'),
  'family-close': yup.string().required('กรุณาเลือกในครอบครัวนักเรียนสนิทสนมใครมากที่สุด'),
  'problem-who': yup.string().required('กรุณาเลือกเมื่อมีปัญหา นักเรียนจะปรึกษาใคร'),
  'behavior-drug': yup.string().required('กรุณาเลือกพฤติกรรมใช้สารเสพติด'),
  'behavior-violence': yup.string().required('กรุณาเลือกพฤติกรรมใช้ความรุนแรง'),
  'sexual-behavior': yup.string().required('กรุณาเลือกพฤติกรรมทางเพศ'),
  'addict-game': yup.string().required('กรุณาเลือกพฤติกรรมติดเกมส์'),
  'internet-access': yup.string().required('กรุณาเลือกการเข้าถึงสื่อคอมพิวเตอร์และอินเตอร์เน็ตที่บ้าน'),
  'mobile-phone': yup.string().required('กรุณาเลือกการใช้โทรศัพท์มือถือ'),
});